### ISSUE TITLE
the nuxt/dist/nuxt.js source map are not working with Debug node in Chrome 

### ISSUE THREAD

**Issue by lazycrazy** [nuxt-community/starter-template#11]
when i use node --inspect debug in chrome devtools
the nuxt/dist/nuxt.js file's source map are not  working 
chrome show "source map detected",but in the sources panel only have "no domain" workspace
os : win10 (64)
node: v7.7.1
chrome: 57.0.2987.98 (64)
webpack:2.2.1
![image](https://cloud.githubusercontent.com/assets/3195978/23883363/706949a4-08a1-11e7-8ab5-a341dfebe171.png)
![image](https://cloud.githubusercontent.com/assets/3195978/23883412/b002853a-08a1-11e7-97b3-c22b6ceb41af.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c9">#c9</a>)</em></sub></div>

**Comment by atinux** [comment]
I see, but why do you need the source maps @lazycrazy ?

**Comment by ssendev** [comment]
@Atinux because it makes development a lot nicer. 

When runing ` node --inspect node_modules/.bin/nuxt` and then attaching with your editor (i am using visual studio code but others allow it too) it is possible to set breakpoints. But they only work when sourcemaps are set up correctly. The other way around is possible too. When an exception is thrown your editor could put you directly to the location where it happened. But without proper sourcemaps will open something like 0.nuxt.bundle.xxx.js and then you have to recognize the file you want to open and then open it.

More or less the same applies for in browser debugging.

**Comment by alterhu2020** [comment]
@ssendev I had found that use like below command could be used to debug the `nuxt` application.
`C:\nodejs\node.exe --inspect-brk=56017 -r babel-register C:\ProjectStack\nuxtjs20170926\node_modules\nuxt\bin\nuxt-dev`

but you notice that nuxt using `babel-preset-env`, and bebel default preset is`vue-app`.
so you need to  create a babel file in the project root ,named as `.babelrc`, content could be like below:
```
{
  "presets": [
    "vue-app"
  ]
}
```
Then go on debug it should met you need .
