### ISSUE TITLE
"About" page error

### ISSUE THREAD

**Issue by quilin** [nuxt-community/starter-template#13]
Seems like the "about" page (though it's not referenced to anymore) uses an old data contract, expecting the context to be received. Probably, need to use asyncData instead of data to render things properly.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/starter-template/issues/c17">#c17</a>)</em></sub></div>

**Comment by ausir0726** [comment]
vue init will use git clone a version in your home directory , like ~/.vue-templates folder
you can kill it , and when you use vue init will get a latest version template ...

first time vue init => git clone nuxt/starter
sec time vue init => git clone nuxt/starter to first time folder
so , if online repo have delete some file ...
your template will keep that file until you delete ..

I was report this issue , but vue-init said , that be design .
official said best practice is kill that folder when you want a new template .

for nuxt/starter
0.9.9 have about.vue => data ({req}) ==> your downloaded local temp
0.10.0 about.vue modify data ({req}) to asyncData({req}) by @Atinux => you don't got this .
0.10.5 delete about.vue by @alexchopin  =>  you re-init project , but outdate about.vue still in your temp folder .

this issue came from vue-cli
https://github.com/vuejs/vue-cli/issues/397

you should clean that folder when template update

**Comment by atinux** [comment]
@alexchopin

**Comment by alexchopin** [comment]
@ausir0726 is right, you need to delete the folder before use vue-init again.

**Comment by ausir0726** [comment]
@alexchopin 
I don't understand why just use git clone repo , and without delete outdate data .
It will be faster ? and if repo is in vue-templates folder , why can't use git pull ?

anyway ..

write vue template should be avoid delete file ... ( update is fine )
that file will in your template folder , until you deleted ...
